Start tunnels actions (#2)
* feat(create-workflows): add several data support

* refactor: description and types fixes

* feat: Run tunnel server action

* fix: Fides version name

* fix(run-tunnel-server): create directory recursive

* fix(run-tunnel-server): use inputs.target variable in Set offers by target step

* fix: added missing quote

* feat: Added run tunnel client nodejs action

* feat: Make run-tunnel-client action general

* feat: Upload file action

* fix: Check folder exists

* fix: Fixed workdirs

* fix: using basename in files upload

* fix: Key and cert vice versa

* fix: Comment fixes

diff --git a/actions/create-workflows/action.yaml b/actions/create-workflows/action.yaml
--- a/actions/create-workflows/action.yaml
+++ b/actions/create-workflows/action.yaml
@@ -1,30 +1,27 @@
 name: Create workflow
+description: Create workflow with spctl tool and return created order numbers
 
 inputs:
+  spctl_config_file:
+    description: Path to spctl config file
+    default: ./config.json
   tee_offers:
-    type: string
     description: tee offers separated by comma (eg. 1,3)
     required: true
-  base-image-offer:
-    type: string
+  base_image:
     description: Base image offer number
   solution:
-    type: string
     description: Solution offer number or path to file with solution resource
     required: true
   data:
-    type: string
-    description: Data offer number or path to data resource file
+    description: Data offer number or path to data resource file. If data several, separate by comma (103,./data-settings.json)
     required: true
   storage_offer:
-    type: string
     description: Storage offer number
     required: true
   previous_orders:
-    type: string
     description: Previous order numbers to cancel, separated by comma (eg. 100,102)
   min_rent_minutes:
-    type: string
     description: How long order should run
     default: '129600'
 
@@ -36,19 +33,14 @@ outputs:
 runs:
   using: composite
   steps:
-    - name: Check SPCTL and validate input
+    - name: Check spctl
+      uses: Super-Protocol/sp-build-tools/actions/check-spctl@v1
+      with:
+        spctl_config_file: ${{ inputs.spctl_config_file }}
+
+    - name: Validate input
       shell: bash
       run: |
-        if [ ! -f "./spctl" ]; then
-          echo "Error: spctl file is missing."
-          exit 1
-        fi
-
-        if [ ! -f "./config.json" ]; then
-          echo "Error: config.json file is missing."
-          exit 1
-        fi
-
         if [ ! "$(echo ${{ inputs.solution }} | grep -E '[0-9]')" ]; then
           if [ ! -f "${{ inputs.solution }}" ]; then
             echo "Error: File specified by inputs.solution does not exist."
@@ -56,12 +48,20 @@ runs:
           fi
         fi
 
-        if [ ! "$(echo ${{ inputs.data }} | grep -E '[0-9]')" ]; then
-          if [ ! -f "${{ inputs.data }}" ]; then
-            echo "Error: File specified by inputs.data does not exist."
-            exit 1
+        # Split inputs.data into an array using a comma as a separator
+        IFS=',' read -ra data_items <<< "${{ inputs.data }}"
+
+        # Loop through each item in the array
+        for item in "${data_items[@]}"; do
+          # Check if the item is a number
+          if ! [[ "$item" =~ ^[0-9]+$ ]]; then
+            # If it's not a number, check if it's a file path and if the file exists
+            if [ ! -f "$item" ]; then
+              echo "Error: File specified by inputs.data ($item) does not exist."
+              exit 1
+            fi
           fi
-        fi
+        done
 
     - name: Cancel previous orders
       shell: bash
@@ -72,7 +72,7 @@ runs:
 
         for orderId in "${orderIds[@]}"; do
           echo "Cancelling order $orderId"
-          ./spctl orders cancel $orderId || true
+          ./spctl orders cancel $orderId --config ${{ inputs.spctl_config_file }} || true
         done
 
     - name: Create workflows
@@ -90,7 +90,18 @@ runs:
             COMMAND="$COMMAND --solution ${{ inputs.base_image }}"
           fi
 
-          COMMAND="$COMMAND --solution ${{ inputs.solution }} --data ${{ inputs.data }} --storage ${{ inputs.storage_offer }} --orders-limit 10000 --min-rent-minutes ${{ inputs.min_rent_minutes }} > workflow_result.txt"
+          COMMAND="$COMMAND --solution ${{ inputs.solution }}"
+
+          # Split inputs.data into an array using a comma as a separator
+          IFS=',' read -ra data_items <<< "${{ inputs.data }}"
+
+          # Loop through each item in the array
+          for item in "${data_items[@]}"; do
+            # Append "--data $item" to the COMMAND variable for both numbers and file paths
+            COMMAND="$COMMAND --data $item"
+          done
+
+          COMMAND="$COMMAND --storage ${{ inputs.storage_offer }} --orders-limit 10000 --min-rent-minutes ${{ inputs.min_rent_minutes }} --config ${{ inputs.spctl_config_file }} > workflow_result.txt"
 
           echo "COMMAND=$COMMAND"
 
